'use client'
import { Inter } from "next/font/google";
import { ThemeProvider } from '@mui/material/styles';
import "./globals.css";
import { createTheme } from '@mui/material/styles';

const theme = createTheme({
  palette: {
    primary: {
      main: '##EE6093', // Your primary color
    },
    secondary: {
      main: '#ffc107', // Your secondary color
    },
  },
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
      <body className={`${inter.className} bg-[#EEF0F6]`}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
