<<<<<<< HEAD
'use client'
import { Inter } from "next/font/google";
import { ThemeProvider } from '@mui/material/styles';
=======
import { Inter, Poppins } from "next/font/google";
>>>>>>> c4d3f08c9bfccfc1d5be3e02039861af1df2e7b9
import "./globals.css";
import { createTheme } from '@mui/material/styles';

const theme = createTheme({
  palette: {
    primary: {
      main: '##EE6093', // Your primary color
    },
    secondary: {
      main: '#ffc107', // Your secondary color
    },
  },
});

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <ThemeProvider theme={theme}>
      <body className={`${inter.className} bg-[#EEF0F6]`}>{children}</body>
      </ThemeProvider>
=======
      <body className={`${poppins.variable} bg-[#EEF0F6]`}>{children}</body>
>>>>>>> c4d3f08c9bfccfc1d5be3e02039861af1df2e7b9
    </html>
  );
}
